Repository AlexandreCK/alien-abduction-tours, pull requests merged in 2025-04, with the labels that each got.

#11 feat(landing page): add preliminar landing page structure without assets
  index.html
  package-lock.json
  src/App.jsx
  src/components/DestinationCard.jsx
  src/components/DestinationsSection.jsx
  src/components/FeatureCard.jsx
  src/components/FeaturesSection.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/HeroSection.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
Labels: development

#13 fix(dependencies): resolve Tailwind CSS setup issues
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/index.css
  tailwind.config.js
Labels: enhancement

#8 feat(assets): add initial assets
  src/assets/background-a-lot-to-orange-stars.png
  src/assets/background-black-hole.png
  src/assets/background-blue-planet.png
  src/assets/background-lights-in-space.png
  src/assets/background-saturn-and-star.png
  src/assets/logo-v1.png
  src/assets/mars.png
  src/assets/moon.png
  src/assets/solar-system-planets.png
  src/assets/uranus.png
Labels: development

#18 docs(team): add roles documentation and workflow guidelines
  docs/role_definitions.md
Labels: documentation

#21 feat(setup): initialize backend, database, and Docker configuration
  .gitignore
  backend/.env.example
  backend/Dockerfile
  backend/db.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.js
  backend/server.js
  db/init/01_schema.sql
  docker-compose.yml
  eslint.config.js
Labels: development

#20 ci(linting): update workflow configuration
  .github/workflows/lint.yml
Labels: enhancement
